[project]
name = "Arkival"
version = "1.1.20"
description = "AI Agent Workflow Orchestration System for seamless knowledge transfer between AI agents and human developers"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
